if exist obj%1_%2_x86 rd /s /q obj%1_%2_x86
if exist objfre_wnet_x86 rd /s /q objfre_wnet_x86
if exist objchk_wnet_x86 rd /s /q objchk_wnet_x86
if exist objfre_wxp_x86 rd /s /q objfre_wxp_x86
if exist objchk_wxp_x86 rd /s /q objchk_wxp_x86
if exist objfre_w2k_x86 rd /s /q objfre_w2k_x86
if exist objchk_w2k_x86 rd /s /q objchk_w2k_x86
if exist objfre_wnet_amd64 rd /s /q objfre_wnet_amd64
if exist objchk_wnet_amd64 rd /s /q objchk_wnet_amd64
if exist objfre_wxp_amd64 rd /s /q objfre_wxp_amd64
if exist objchk_wxp_amd64 rd /s /q objchk_wxp_amd64
if exist objfre_w2k_amd64 rd /s /q objfre_w2k_amd64
if exist objchk_w2k_amd64 rd /s /q objchk_w2k_amd64
if exist Debug rd /s /q Debug
if exist Release rd /s /q Release